<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LabTestsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lab_tests')->delete();
        
        \DB::table('lab_tests')->insert(array (
            0 => 
            array (
                'id' => 1,
                'department_id' => 3,
                'profile_id' => NULL,
                'code' => 'A10',
                'tests' => 'HB',
                'male_min_range' => 1.0,
                'male_max_range' => 2.0,
                'female_min_range' => 2.0,
                'female_max_range' => 4.0,
                'child_min_range' => 2.0,
                'child_max_range' => 4.0,
                'male_amber_min_range' => 3.0,
                'male_amber_max_range' => 4.0,
                'female_amber_min_range' => 3.0,
                'female_amber_max_range' => 5.0,
                'child_amber_min_range' => 5.0,
                'child_amber_max_range' => 6.0,
                'male_red_min_range' => 6.0,
                'male_red_max_range' => 7.0,
                'female_red_min_range' => 3.0,
                'female_red_max_range' => 5.0,
                'child_red_min_range' => 4.0,
                'child_red_max_range' => 6.0,
                'test_result_type' => 'Range',
                'unit' => 'cells/dl',
                'price' => '100',
                'created_at' => '2023-02-07 12:05:49',
                'updated_at' => '2023-02-07 12:05:49',
            ),
            1 => 
            array (
                'id' => 2,
                'department_id' => 1,
                'profile_id' => 1,
                'code' => 'A11',
                'tests' => 'SGOT',
                'male_min_range' => 1.0,
                'male_max_range' => 3.0,
                'female_min_range' => 3.0,
                'female_max_range' => 3.0,
                'child_min_range' => 3.0,
                'child_max_range' => 3.0,
                'male_amber_min_range' => 4.0,
                'male_amber_max_range' => 5.0,
                'female_amber_min_range' => 33.0,
                'female_amber_max_range' => 3.0,
                'child_amber_min_range' => 3.0,
                'child_amber_max_range' => 3.0,
                'male_red_min_range' => 3.0,
                'male_red_max_range' => 3.0,
                'female_red_min_range' => 3.0,
                'female_red_max_range' => 3.0,
                'child_red_min_range' => 3.0,
                'child_red_max_range' => 3.0,
                'test_result_type' => 'Range',
                'unit' => 'cells/dl',
                'price' => '100',
                'created_at' => '2023-02-07 12:06:36',
                'updated_at' => '2023-02-07 12:06:36',
            ),
            2 => 
            array (
                'id' => 3,
                'department_id' => 1,
                'profile_id' => 1,
                'code' => 'A12',
                'tests' => 'SGPT',
                'male_min_range' => 1.0,
                'male_max_range' => 1.0,
                'female_min_range' => 1.0,
                'female_max_range' => 1.0,
                'child_min_range' => 1.0,
                'child_max_range' => 1.0,
                'male_amber_min_range' => 1.0,
                'male_amber_max_range' => 1.0,
                'female_amber_min_range' => 1.0,
                'female_amber_max_range' => 1.0,
                'child_amber_min_range' => 1.0,
                'child_amber_max_range' => 1.0,
                'male_red_min_range' => 1.0,
                'male_red_max_range' => 1.0,
                'female_red_min_range' => 1.0,
                'female_red_max_range' => 1.0,
                'child_red_min_range' => 1.0,
                'child_red_max_range' => 1.0,
                'test_result_type' => 'Range',
                'unit' => 'cells/dl',
                'price' => '100',
                'created_at' => '2023-02-07 12:07:04',
                'updated_at' => '2023-02-07 12:07:04',
            ),
            3 => 
            array (
                'id' => 4,
                'department_id' => 2,
                'profile_id' => NULL,
                'code' => 'A13',
                'tests' => 'HIV',
                'male_min_range' => NULL,
                'male_max_range' => NULL,
                'female_min_range' => NULL,
                'female_max_range' => NULL,
                'child_min_range' => NULL,
                'child_max_range' => NULL,
                'male_amber_min_range' => NULL,
                'male_amber_max_range' => NULL,
                'female_amber_min_range' => NULL,
                'female_amber_max_range' => NULL,
                'child_amber_min_range' => NULL,
                'child_amber_max_range' => NULL,
                'male_red_min_range' => NULL,
                'male_red_max_range' => NULL,
                'female_red_min_range' => NULL,
                'female_red_max_range' => NULL,
                'child_red_min_range' => NULL,
                'child_red_max_range' => NULL,
                'test_result_type' => 'Value',
                'unit' => NULL,
                'price' => '100',
                'created_at' => '2023-02-07 12:07:26',
                'updated_at' => '2023-02-07 12:07:26',
            ),
            4 => 
            array (
                'id' => 5,
                'department_id' => 3,
                'profile_id' => NULL,
                'code' => 'A14',
                'tests' => 'TC',
                'male_min_range' => 2.0,
                'male_max_range' => 3.0,
                'female_min_range' => 5.0,
                'female_max_range' => 5.0,
                'child_min_range' => 7.0,
                'child_max_range' => 7.0,
                'male_amber_min_range' => 3.0,
                'male_amber_max_range' => 3.0,
                'female_amber_min_range' => 5.0,
                'female_amber_max_range' => 5.0,
                'child_amber_min_range' => 7.0,
                'child_amber_max_range' => 7.0,
                'male_red_min_range' => 3.0,
                'male_red_max_range' => 3.0,
                'female_red_min_range' => 5.0,
                'female_red_max_range' => 5.0,
                'child_red_min_range' => 7.0,
                'child_red_max_range' => 7.0,
                'test_result_type' => 'Range',
                'unit' => 'cells/dl',
                'price' => '100',
                'created_at' => '2023-02-07 12:08:48',
                'updated_at' => '2023-02-07 12:08:48',
            ),
            5 => 
            array (
                'id' => 6,
                'department_id' => 1,
                'profile_id' => NULL,
                'code' => 'A125',
                'tests' => 'X-ray',
                'male_min_range' => NULL,
                'male_max_range' => NULL,
                'female_min_range' => NULL,
                'female_max_range' => NULL,
                'child_min_range' => NULL,
                'child_max_range' => NULL,
                'male_amber_min_range' => NULL,
                'male_amber_max_range' => NULL,
                'female_amber_min_range' => NULL,
                'female_amber_max_range' => NULL,
                'child_amber_min_range' => NULL,
                'child_amber_max_range' => NULL,
                'male_red_min_range' => NULL,
                'male_red_max_range' => NULL,
                'female_red_min_range' => NULL,
                'female_red_max_range' => NULL,
                'child_red_min_range' => NULL,
                'child_red_max_range' => NULL,
                'test_result_type' => 'Image',
                'unit' => NULL,
                'price' => '100',
                'created_at' => '2023-02-07 14:20:55',
                'updated_at' => '2023-02-07 14:20:55',
            ),
            6 => 
            array (
                'id' => 7,
                'department_id' => 1,
                'profile_id' => NULL,
                'code' => '001',
                'tests' => 'Blood Group Test',
                'male_min_range' => NULL,
                'male_max_range' => NULL,
                'female_min_range' => NULL,
                'female_max_range' => NULL,
                'child_min_range' => NULL,
                'child_max_range' => NULL,
                'male_amber_min_range' => NULL,
                'male_amber_max_range' => NULL,
                'female_amber_min_range' => NULL,
                'female_amber_max_range' => NULL,
                'child_amber_min_range' => NULL,
                'child_amber_max_range' => NULL,
                'male_red_min_range' => NULL,
                'male_red_max_range' => NULL,
                'female_red_min_range' => NULL,
                'female_red_max_range' => NULL,
                'child_red_min_range' => NULL,
                'child_red_max_range' => NULL,
                'test_result_type' => 'Value',
                'unit' => NULL,
                'price' => '1000',
                'created_at' => '2023-02-09 14:08:45',
                'updated_at' => '2023-02-09 14:08:45',
            ),
        ));
        
        
    }
}