<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TeamsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teams')->delete();
        
        \DB::table('teams')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'slug' => 'Dr.-Som-Lal-Subedi-101-3Iy',
                'member_id' => '101',
                'position' => 'Ex-Chief Secretary, GoN',
                'name' => 'Dr. Som Lal Subedi',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'somnath-sir_1669964738.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/somnath-sir_1669964738.jpg',
                'created_at' => '2022-12-02 12:50:38',
                'updated_at' => '2022-12-02 12:50:38',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'slug' => 'Jiba-Lamichhane-102-Kkq',
                'member_id' => '102',
                'position' => 'Entrepreneur, Former PresidentICC, NRNA',
                'name' => 'Jiba Lamichhane',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'jiba-sir_1669964771.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/jiba-sir_1669964771.jpg',
                'created_at' => '2022-12-02 12:51:11',
                'updated_at' => '2022-12-02 12:51:11',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'slug' => 'Thakur-Gyawali-103-8IF',
                'member_id' => '103',
                'position' => 'Ex. IGP, Nepal Police',
                'name' => 'Thakur Gyawali',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'thakur-sir_1669964816.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/thakur-sir_1669964816.jpg',
                'created_at' => '2022-12-02 12:51:56',
                'updated_at' => '2022-12-02 12:51:56',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'slug' => 'Mahabir-Pun-104-wRo',
                'member_id' => '104',
                'position' => 'Researcher, National Innovation Center',
                'name' => 'Mahabir Pun',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'mahabir-sir_1669964856.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/mahabir-sir_1669964856.jpg',
                'created_at' => '2022-12-02 12:52:36',
                'updated_at' => '2022-12-02 12:52:36',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'slug' => 'Suraj-Vaidya-105-Yvx',
                'member_id' => '105',
                'position' => 'Ex. President, FNCCI',
                'name' => 'Suraj Vaidya',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'suraj-vaidya-sir_1669964896.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/suraj-vaidya-sir_1669964896.jpg',
                'created_at' => '2022-12-02 12:53:16',
                'updated_at' => '2022-12-02 12:53:16',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 2,
                'slug' => 'Dr.-Jageshwor-Gautam-201-j7q',
                'member_id' => '201',
                'position' => 'Consultant Gynaecologist & Obstetrician',
                'name' => 'Dr. Jageshwor Gautam',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'jageshwor-sir_1669969325.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/jageshwor-sir_1669969325.jpg',
                'created_at' => '2022-12-02 14:07:05',
                'updated_at' => '2022-12-02 14:07:05',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 2,
                'slug' => 'Dr.-Toran-K.C.-202-mBK',
                'member_id' => '202',
                'position' => 'HOD, ENT-Head & Neck Surgery, Nepal Mediciti Hospital',
                'name' => 'Dr. Toran K.C.',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'toran-sir_1669969369.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/toran-sir_1669969369.jpg',
                'created_at' => '2022-12-02 14:07:49',
                'updated_at' => '2022-12-02 14:07:49',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 2,
                'slug' => 'Prof.-Dr.-Rajendra-Koju-203-kbv',
                'member_id' => '203',
                'position' => 'Dean, KUSMS-Dhulikhel Hospital',
                'name' => 'Prof. Dr. Rajendra Koju',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'rajendra-sir_1669969406.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/rajendra-sir_1669969406.jpg',
                'created_at' => '2022-12-02 14:08:26',
                'updated_at' => '2022-12-02 14:08:26',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 2,
                'slug' => 'Dr.-Anil-Baral-204-GaP',
                'member_id' => '204',
                'position' => 'Consultant Physician and Nephrologist',
                'name' => 'Dr. Anil Baral',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'dranil-sir_1669969447.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/dranil-sir_1669969447.jpg',
                'created_at' => '2022-12-02 14:09:07',
                'updated_at' => '2022-12-02 14:09:07',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 2,
                'slug' => 'Dr.-Bishnu-Datta-Poudel-205-T9a',
                'member_id' => '205',
                'position' => 'Executive Director, Bhaktapur Cancer Hospital',
                'name' => 'Dr. Bishnu Datta Poudel',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'bishnu-sir_1669969486.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/bishnu-sir_1669969486.jpg',
                'created_at' => '2022-12-02 14:09:46',
                'updated_at' => '2022-12-02 14:09:46',
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'slug' => 'Dr.-Prakash-Kayastha-206-bcM',
                'member_id' => '206',
                'position' => 'Consultant Radiologist',
                'name' => 'Dr. Prakash Kayastha',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'drprakash-sir_1669969528.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/drprakash-sir_1669969528.jpg',
                'created_at' => '2022-12-02 14:10:28',
                'updated_at' => '2022-12-02 14:10:28',
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 2,
                'slug' => 'Prof.-Dr.-Ramesh-Makaju-207-IBl',
                'member_id' => '207',
                'position' => 'Administrative Director, KUSMSDhulikhel Hospital',
                'name' => 'Prof. Dr. Ramesh Makaju',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'drramesh-sir_1669969572.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/drramesh-sir_1669969572.jpg',
                'created_at' => '2022-12-02 14:11:12',
                'updated_at' => '2022-12-02 14:11:12',
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 3,
                'slug' => 'Mahendra-P.-Shrestha-301-dpg',
                'member_id' => '301',
                'position' => 'Ex.DG, Department of Health Council',
                'name' => 'Mahendra P. Shrestha',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'mahendra-sirr_1669969609.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/mahendra-sirr_1669969609.jpg',
                'created_at' => '2022-12-02 14:11:49',
                'updated_at' => '2022-12-02 14:11:49',
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 3,
                'slug' => 'Dr.-Narbada-Thapa-302-IqA',
                'member_id' => '302',
            'position' => 'Deputy Principal/Faculty Member, Institute of crisis Management Studies(ICMS)',
                'name' => 'Dr. Narbada Thapa',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'narnda-maam_1669969659.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/narnda-maam_1669969659.jpg',
                'created_at' => '2022-12-02 14:12:39',
                'updated_at' => '2022-12-02 14:12:39',
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 3,
                'slug' => 'Guna-Raj-Luitel-303-MfQ',
                'member_id' => '303',
                'position' => 'Cheif Editor, Nagarik Daily',
                'name' => 'Guna Raj Luitel',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'gun-sir_1669969699.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/gun-sir_1669969699.jpg',
                'created_at' => '2022-12-02 14:13:19',
                'updated_at' => '2022-12-02 14:13:19',
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 3,
                'slug' => 'Dr.-Aruna-Uprety-304-2IR',
                'member_id' => '304',
                'position' => 'President, Nepal Public Health Foundation',
                'name' => 'Dr. Aruna Uprety',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'aruna-maam_1669969734.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/aruna-maam_1669969734.jpg',
                'created_at' => '2022-12-02 14:13:54',
                'updated_at' => '2022-12-02 14:13:54',
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 3,
                'slug' => 'Prof.Dr.-Fatta-Bdr.-K.C-305-Voi',
                'member_id' => '305',
                'position' => 'Ex. Chairman, Insurance Board Nepal',
                'name' => 'Prof.Dr. Fatta Bdr. K.C',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'fatta-sir_1669969766.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/fatta-sir_1669969766.jpg',
                'created_at' => '2022-12-02 14:14:26',
                'updated_at' => '2022-12-02 14:14:26',
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 3,
                'slug' => 'Nawaraj-Paudel-306-gHP',
                'member_id' => '306',
                'position' => 'Reader, CDCSIT, Tribhuvan University',
                'name' => 'Nawaraj Paudel',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'nawaraj-sir_1669969820.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/nawaraj-sir_1669969820.jpg',
                'created_at' => '2022-12-02 14:15:20',
                'updated_at' => '2022-12-02 14:15:20',
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 3,
                'slug' => 'Adv.-Om-Aryal-307-iVP',
                'member_id' => '307',
                'position' => 'Legal Advisor, Kathmandu Metropolitan City',
                'name' => 'Adv. Om Aryal',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'om-sir_1669969858.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/om-sir_1669969858.jpg',
                'created_at' => '2022-12-02 14:15:58',
                'updated_at' => '2022-12-02 14:15:58',
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 4,
                'slug' => 'Rupesh-Shrestha-401-oj0',
                'member_id' => '401',
                'position' => 'TV Journalist',
                'name' => 'Rupesh Shrestha',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'rupesh-sir_1669969900.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/rupesh-sir_1669969900.jpg',
                'created_at' => '2022-12-02 14:16:40',
                'updated_at' => '2022-12-02 14:16:40',
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 4,
                'slug' => 'Maheshwor-Maharjan-402-Ot8',
                'member_id' => '402',
                'position' => '13th Dharmashree Championship',
                'name' => 'Maheshwor Maharjan',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'maheshwor-sir_1669969935.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/maheshwor-sir_1669969935.jpg',
                'created_at' => '2022-12-02 14:17:15',
                'updated_at' => '2022-12-02 14:17:15',
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 4,
                'slug' => 'Amar-Neupane-403-XF4',
                'member_id' => '403',
                'position' => 'Writer/Novelist, Madan Puraskar Winner',
                'name' => 'Amar Neupane',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'amar-sir_1669969970.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/amar-sir_1669969970.jpg',
                'created_at' => '2022-12-02 14:17:50',
                'updated_at' => '2022-12-02 14:17:50',
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 4,
                'slug' => 'Srinkhala-Khatiwada-404-Mnh',
                'member_id' => '404',
                'position' => 'Miss Nepal World 2018',
                'name' => 'Srinkhala Khatiwada',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'shrinkhala-maam_1669970005.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/shrinkhala-maam_1669970005.jpg',
                'created_at' => '2022-12-02 14:18:25',
                'updated_at' => '2022-12-02 14:18:25',
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 4,
                'slug' => 'Pushkar-Shah-405-LMV',
                'member_id' => '405',
                'position' => 'World Cyclist',
                'name' => 'Pushkar Shah',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'puskar-sir_1669970048.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/puskar-sir_1669970048.jpg',
                'created_at' => '2022-12-02 14:19:08',
                'updated_at' => '2022-12-02 14:19:08',
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 4,
                'slug' => 'Sipora-Gurung-406-Te8',
                'member_id' => '406',
                'position' => 'Volleyball Player, Nepal National Team',
                'name' => 'Sipora Gurung',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'sipora-maam_1669970084.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/sipora-maam_1669970084.jpg',
                'created_at' => '2022-12-02 14:19:44',
                'updated_at' => '2022-12-02 14:19:44',
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 4,
                'slug' => 'Keki-Adhikari-407-gj2',
                'member_id' => '407',
                'position' => 'Actress',
                'name' => 'Keki Adhikari',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'keki-maam_1669970122.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/keki-maam_1669970122.jpg',
                'created_at' => '2022-12-02 14:20:22',
                'updated_at' => '2022-12-02 14:20:22',
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 4,
                'slug' => 'Tika-Prasai-408-Sfe',
                'member_id' => '408',
                'position' => 'Singer',
                'name' => 'Tika Prasai',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'tika-maam_1669970149.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/tika-maam_1669970149.jpg',
                'created_at' => '2022-12-02 14:20:49',
                'updated_at' => '2022-12-02 14:20:49',
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 4,
                'slug' => 'Shakti-Gauchan-409-wRK',
                'member_id' => '409',
                'position' => 'Cricketer, Nepal National Team',
                'name' => 'Shakti Gauchan',
                'email' => 'demo@gmail.com',
                'phone_no' => '9860310410',
                'address' => 'Kathmandu',
                'image' => 'shakti-sir_1669970184.jpg',
                'image_path' => 'https://demo.ghargharmadoctor.com/storage/images/shakti-sir_1669970184.jpg',
                'created_at' => '2022-12-02 14:21:24',
                'updated_at' => '2022-12-02 14:21:24',
            ),
        ));
        
        
    }
}